const majors={it:'Ақпараттық технологиялар',design:'Дизайн',finance:'Қаржы және экономика',education:'Педагогика',marketing:'Маркетинг'};
const data={it:[['Telegram-бот құрастыру',6500,150,'Python'],['Веб-бетті жасау',7000,180,'HTML/CSS'],['Қосымшаны тестілеу',5500,120,'QA']],design:[['Әлеуметтік желіге баннер',5000,120,'Figma'],['Логотип эскизін жасау',6500,180,'Дизайн'],['Презентация безендіру',4000,120,'Canva']],finance:[['Excel есебін жасау',6000,150,'Excel'],['Шығындарды талдау',5500,180,'Талдау'],['Деректерді енгізу',3500,120,'Кестелер']],education:[['Оқушыға математика түсіндіру',4500,120,'Оқыту'],['Сабақ жоспарын дайындау',5000,150,'Әдістеме'],['Оқу материалын жасау',4000,120,'Педагогика']],marketing:[['Контент-жоспар әзірлеу',6000,150,'SMM'],['Әлеуметтік желіге мәтін жазу',4500,120,'Копирайтинг'],['Нарыққа шағын зерттеу',6500,180,'Зерттеу']]};
let state=JSON.parse(localStorage.getItem('qadam-state')||'null')||{major:'it',skills:'',from:'14:00',to:'18:00',apps:[],balance:0};
const el=id=>document.getElementById(id);const save=()=>localStorage.setItem('qadam-state',JSON.stringify(state));const fmt=n=>n.toLocaleString('kk-KZ')+' ₸';
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav button').forEach((x,i)=>x.classList.toggle('active',['home','jobs','schedule','income','profile'][i]===id));render();window.scrollTo(0,0)}
function free(){const [h,m]=state.from.split(':').map(Number),[a,b]=state.to.split(':').map(Number);return (a*60+b)-(h*60+m)}
function card(j,i){const id=state.major+'-'+i,app=state.apps.find(x=>x.id===id),fits=free()>=j[2];return `<div class="card"><div class="line"><h2>${j[0]}</h2><span class="pill">${j[3]}</span></div><p class="muted">${j[2]/60} сағ · ${fits?'Кестеге сәйкес келеді':'Уақыт жеткіліксіз'}</p><div class="line"><span class="price">${fmt(j[1])}</span><button class="btn" ${app||!fits?'disabled':''} onclick="apply(${i})">${app?'Өтінім берілді':'Өтінім беру'}</button></div></div>`}
function apply(i){const j=data[state.major][i];state.apps.push({id:state.major+'-'+i,title:j[0],pay:j[1],status:'Күтілуде'});save();render();alert('Өтінім жіберілді! (демо)')}
function complete(id){const a=state.apps.find(x=>x.id===id);if(!a||a.status==='Орындалды')return;a.status='Орындалды';state.balance+=a.pay;save();render()}
function saveSchedule(){if(free()<=0)return alert('Уақыт аралығын дұрыс таңдаңыз');state.from=el('from').value;state.to=el('to').value;save();render();alert('Кесте сақталды!')}
function saveProfile(){state.major=el('major').value;state.skills=el('skills').value;save();go('home')}
function render(){el('major').value=state.major;el('skills').value=state.skills;el('from').value=state.from;el('to').value=state.to;el('homeMajor').textContent=majors[state.major];el('homeWindow').textContent=`Бос уақыт: ${state.from}–${state.to}`;const jobs=data[state.major];el('featured').innerHTML=jobs.slice(0,2).map(card).join('');el('joblist').innerHTML=jobs.map(card).join('');el('matches').innerHTML=`<p class="notice">Бос уақытқа сай ${jobs.filter(j=>j[2]<=free()).length} тапсырма табылды</p>`+jobs.filter(j=>j[2]<=free()).map(j=>card(j,jobs.indexOf(j))).join('');el('balance').textContent=fmt(state.balance);el('applications').innerHTML=state.apps.length?state.apps.map(a=>`<div class="card"><h2>${a.title}</h2><p class="status">${a.status}</p><div class="line"><b>${fmt(a.pay)}</b>${a.status==='Орындалды'?'✓':`<button class="btn outline" onclick="complete('${a.id}')">Орындалды деп белгілеу</button>`}</div></div>`).join(''):'<div class="card">Әзірге өтінім жоқ.</div>';el('portfolio').textContent=state.apps.filter(a=>a.status==='Орындалды').map(a=>a.title).join(' · ')||'Әзірге орындалған тапсырма жоқ.'}
render();
